
services:

  app:
    image: petclinic:latest
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    networks:
      - petclinic
    environment:
      - MYSQL_URL=jdbc:mysql://mysqlpetclinic:3306/petclinic

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    networks:
      petclinic:
        aliases:
          - mysqlpetclinic
  
networks:
  petclinic:
